# Generated by Django 5.1.2 on 2024-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.CharField(default='No comment', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='No first name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='No last Name', max_length=200),
            preserve_default=False,
        ),
    ]
