# Generated by Django 5.1.2 on 2024-11-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_remove_booking_name_remove_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
